// Auto-generated by dynamic_regress/run_pipeline.py.
// RTOSAlgorithm-style wrapper for the identified Pinocchio/CasADi dynamics.
// generated_at: 2026-04-24T18:40:52
// robot_name: 05_urdf
// data_source: real
// real_torque_source: sensed
// parameterization: base
// identification_mode: rigid_body_friction
// nonlinear_compensation: mlp_residual
#pragma once

#include "hansTypes.h"
#include "dynamicsBase.h"

using namespace KDL;

class sevendofDynamics : public dynamicsBase
{
public:
	sevendofDynamics();
	virtual ~sevendofDynamics();

	virtual void setRobotDHParameters
	(
		const EcRealVector& kinematcisParam
	);

	virtual void setGravityVector
	(
		const EcReal gx, const EcReal gy, const EcReal gz
	);

	virtual void calculateGravityJointTorques
	(
		const EcRealVector& q,
		const EcRealVector& parms,
		EcRealVector& tau
	);

	virtual EcBoolean calculateEstimateJointToqrues
	(
		const EcRealVector& q,
		const EcRealVector& dq,
		const EcRealVector& ddq,
		const EcRealVector& parms,
		EcRealVector& tau
	);

	virtual void calculateMomentumEstimatedJointTorques
	(
		const EcRealVector& q,
		const EcRealVector& dq,
		const EcRealVector& ddq,
		const EcRealVector& parms,
		EcRealVector& tau
	);

private:
	static const EcSizeT kNumJoints = 7;
	EcSizeT m_NumJoints;
	EcReal m_gx;
	EcReal m_gy;
	EcReal m_gz;
	EcRealVector m_zeros;
};
